version: '3'

networks:
  personniNetwork:
    driver: bridge

services:
  personniMoveisDB:
    image: postgres:latest
    container_name: personniMoveisDB
    restart: always
    networks: 
      - personniNetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: PersonniMoveis
    ports:
      - "5432:5432"

  spring_api:
    build: "."
    container_name: spring_api
    depends_on: 
      - personniMoveisDB
    networks:
      - personniNetwork
    environment:
      - PORT=8081
      - DB_HOST=personniMoveisDB
      - DB_PORT=5432
      - DB_NAME=PersonniMoveis
      - DB_USER=postgres
      - DB_PASSWORD=1234
    ports:
      - "8081:8081"
  
  # vuejs_app:
  #   build: "./personniMoveisFront"
  #   container_name: vuejs_app
  #   depends_on:
  #     - spring_api
  #   networks:
  #     - personniNetwork
  #   environment:
  #     - PORT=8080
  #     - NODE_ENV=container
  #   ports:
  #     - 8080:8080